### ISSUE TITLE
Network name showing as "unknown" when doing visualize

### ISSUE THREAD

**Issue by Ramaraja** [CiscoZeus/don#37] opened 2016-04-26 10:09 UTC
network name replaced with "unknown" randomly.

**Comment by amsaha** [comment] 2016-04-26 10:17
@Ramaraja can you add a snapshot?

**Comment by Ramaraja** [comment] 2016-04-26 10:25
![2016-04-26 15_54_36-don - openstack dashboard](https://cloud.githubusercontent.com/assets/1433279/14815148/4e5c6b8e-0bc7-11e6-8e4f-7f5c53ebaff6.png)

**Comment by Ramaraja** [comment] 2016-04-29 13:37
Issue root cause: When parsing command "nova list", There are 2 ip entries which is IPv6 and IPv4 i.e(public=2001:db8::5, 172.24.4.4). current logic collecting IP information which is next to '=' symbol. When visualize option triggered its referring with ipv4 ip which is not available in VM info.

**Comment by amsaha** [comment] 2016-04-30 15:49
:+1:

**Comment by amsaha** [comment] 2016-05-03 07:58
@Ramaraja  I just tried it and it seems that the issue is still present.

**Comment by amsaha** [comment] 2016-05-03 09:17
The fix was not present on the setup that I tried on. The issue is actually resolved via pull #39.

**Closed by amsaha** 2016-05-03 09:17 UTC
Labels: bug
